import {
  BsFileRuledFill,
  BsFillHouseAddFill,
  BsFillHousesFill,
} from "react-icons/bs";
import {
  FaBuilding,
  FaCheckCircle,
  FaEdit,
  FaFileAlt,
  FaHeart,
  FaLinkedin,
  FaMinus,
  FaPlus,
  FaPrint,
  FaRegCopy,
  FaRegHeart,
  FaRegTrashAlt,
  FaStar,
  FaUpload,
} from "react-icons/fa";
import { FaFileInvoice, FaMoneyCheck, FaPeopleRoof } from "react-icons/fa6";
import { GrHostMaintenance, GrSchedules } from "react-icons/gr";
import {
  IoIosArrowDown,
  IoIosBed,
  IoIosPaper,
  IoIosPeople,
  IoMdMail,
} from "react-icons/io";
import {
  IoCarSharp,
  IoCloseSharp,
  IoLocationSharp,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoTiktok,
  IoLogoTwitter,
} from "react-icons/io5";
import {
  MdAccountCircle,
  MdAttachMoney,
  MdDashboard,
  MdOutlineClose,
  MdOutlineDone,
  MdOutlinePayment,
  MdOutlinePets,
  MdPermMedia,
} from "react-icons/md";
import { PiBuildingApartmentFill } from "react-icons/pi";
import { RiBillFill } from "react-icons/ri";
import { SlCalender } from "react-icons/sl";
import { TbLogout2 } from "react-icons/tb";
export const Icons = {
  Location: IoLocationSharp,
  Building: FaBuilding,
  Heart: FaHeart,
  FilledHeart: FaRegHeart,
  Upload: FaUpload,
  Facebook: IoLogoFacebook,
  Instagram: IoLogoInstagram,
  Twitter: IoLogoTwitter,
  Tiktok: IoLogoTiktok,
  Close: IoCloseSharp,
  Calender: SlCalender,
  Edit: FaEdit,
  Delete: FaRegTrashAlt,
  Print: FaPrint,
  Plus: FaPlus,
  Minus: FaMinus,
  Copy: FaRegCopy,
  Tik: MdOutlineDone,
  DownArrow: IoIosArrowDown,
  Star: FaStar,
  Bed: IoIosBed,
  Linkedin: FaLinkedin,
  Check: FaCheckCircle,
  dashboard: MdDashboard,
  application: FaFileAlt,
  resident: FaPeopleRoof,
  properties: BsFillHouseAddFill,
  apartment: PiBuildingApartmentFill,
  propertiesList: BsFillHousesFill,
  propertyRules: BsFileRuledFill,
  work: GrHostMaintenance,
  tour: GrSchedules,
  employee: IoIosPeople,
  invoice: FaFileInvoice,
  paymentSetting: MdOutlinePayment,
  subscription: MdAttachMoney,
  account: MdAccountCircle,
  asset: MdPermMedia,
  logout: TbLogout2,
  pets: MdOutlinePets,
  cars: IoCarSharp,
  docs: IoIosPaper,
  check: FaMoneyCheck,
  utility: RiBillFill,
  mail: IoMdMail,
  closeBtn: MdOutlineClose,
};
